spring.application.name=backend

spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# May or may not have to change this line for production; fine for localhost
spring.jpa.hibernate.ddl-auto=update